# Generated by Django 5.2.5 on 2025-09-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='phone_number',
        ),
    ]
