# Generated by Django 5.2.5 on 2025-09-10 12:13

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocauthormodel',
            name='bio_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='blocauthormodel',
            name='bio_uz',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='blocauthormodel',
            name='full_name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='blocauthormodel',
            name='full_name_uz',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogtags',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogtags',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
